---
- hosts: routers
  become: yes
  gather_facts: no
  
  tasks:
    - name: Set OSPF area on all Cisco IOS Routers
      cisco.ios.ios_config:
        lines:
          - router ospf autonomous system 0